name: "Dev-Prod-Destroy"

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  Terraform_Dev:
    name: "Destroy Dev"
    runs-on: ubuntu-latest
    environment: Dev
    defaults:
      run:
        working-directory: ./dev-code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credetials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::045696458263:role/GIT-Terraform-AWS
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        #run: terraform init
        run: terraform init -backend-config="bucket=ck-terra-bucket" -backend-config="key=dev.tfstate" -backend-config="region=ap-south-1"

      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Destroy
        run: terraform destroy --auto-approve        

  Terraform_Prod:
    name: "Destroy Prod"
    runs-on: ubuntu-latest
    needs: Terraform_Dev
    environment: Prod
    defaults:
      run:
        working-directory: ./prod-code

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credetials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::045696458263:role/GIT-Terraform-AWS
          aws-region: ap-south-1
                
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=ck-terra-bucket" -backend-config="key=prod.tfstate" -backend-config="region=ap-south-1"

      - name: Terraform Destroy
        run: terraform destroy --auto-approve
