on:
    workflow_dispatch:
    push:

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest
        environment:
          name: DEV
        permissions:
          id-token: write
          contents: read

        steps:
            - name: clone source code 
              uses: actions/checkout@v4
            - name: Configure AWS credetials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ROLE}}
                aws-region: ap-south-1
            - name: Terraform Init
              run: terraform init
              
            - name: Terraform Plan
              run: terraform plan
              
            - name: Manual Approval
              uses: actions/github-script@v4
              env:
                ENVIRONMENT: DEV
              with:
                script: |
                    github.actions.createApprovalRequest({
                      event: context.eventName,
                      requester: context.actor,
                      head_sha: context.sha,
                      base_sha: context.payload.before,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      event_type: 'APPROVE',
                      client_payload: {
                        environment: ENVIRONMENT
                      }
                    }) 

            - name: Terraform Apply
              if: steps.approval.outputs.approved == 'true'
              run: terraform apply -auto-approve
