on:
    workflow_dispatch:
    push:

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read

        steps:
            - name: Configure AWS credetials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secret.AWS_ROLE}}
                aws-region: ap-south-1
            - name: Terraform Init
              run: terraform init
            - name: Terraform Plan
              run: terraform plan
            - name: Terraform Apply
              run: terraform apply
