name: "Terraform"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Terraform_Plan:
    name: "Terraform_plan"
    runs-on: ubuntu-latest
    environment: Plan
    env:
        role-to-assume: ${{ secrets.AWS_ROLE }}
#    defaults:
#      run:
#        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan



  Terraform_Apply:
    name: "Terraform_Apply"
    runs-on: ubuntu-latest
    needs: [Terraform_Plan]
    environment: Apply
    env:
        role-to-assume: ${{ secrets.AWS_ROLE }}
#    defaults:
#      run:
#        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve


  Terraform_Destroy:
    name: "Terraform_Destroy"
    runs-on: ubuntu-latest
    needs: [Terraform_Apply]
    environment: Destroy
    env:
        role-to-assume: ${{ secrets.AWS_ROLE }}
#    defaults:
#      run:
#        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform apply -destroy --auto-approve
