on:
    workflow_dispatch:
    push:

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read

        steps:
            - name: clone source code 
              uses: actions/checkout@v4
            - name: Configure AWS credetials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ROLE}}
                aws-region: ap-south-1
            - name: Terraform Init
              run: terraform init
              
            - name: Terraform Plan
              run: terraform plan
              
            - name: Manual Approval
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: "chandanvnk1/manual-approval@v2"
              id: approval
              with:
                  message: "Approve to apply Terraform changes"
          
            - name: Terraform Apply
              run: terraform apply -auto-approve
