on:
    workflow_dispatch:
    push:

    permissions:
      id-token: write
      contents: read

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credetials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: arn:aws:iam::045696458263:role/GIT-Terraform-AWS
                aws-region: ap-south-1
