on:
    workflow_dispatch:
    push:

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest
        environment:
          name: DEV
        permissions:
          id-token: write
          contents: read

        steps:
            - name: clone source code 
              uses: actions/checkout@v4
            - name: Configure AWS credetials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ROLE}}
                aws-region: ap-south-1
            - name: Terraform Init
              run: terraform init
              
            - name: Terraform Plan
              run: terraform plan

            - name: Approval
              uses: actions/checkout@v4
              env:
                ENVIRONMENT: DEV

            - name: Terraform Apply
              run: terraform apply -auto-approve
