on:
    workflow-dispatch:
    push:

jobs:
    terraform-deploy:
        runs-on:
        steps:
            -name: Configure AWS credetials
             uses: aws-actions/configure-aws-credentials@v4
             with:
                role-to-assume: arn:aws:iam::045696458263:role/GIT-Terraform-AWS
                aws-region: ap-south-1