name: "Terraform"

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read
jobs:
  Terraform_Plan:
    name: "Terraform_plan"
    runs-on: ubuntu-latest
    environment: Plan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credetials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        #run: terraform init
        run: terraform init -backend-config="bucket=ck-terra-bucket" -backend-config="key=test.tfstate" -backend-config="region=ap-south-1"

      - name: Terraform Plan
        run: terraform plan

  Terraform_Apply:
    name: "Terraform_Apply"
    runs-on: ubuntu-latest
    needs: [Terraform_Plan]
    environment: Apply

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credetials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::045696458263:role/GIT-Terraform-AWS
          aws-region: ap-south-1
                
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=ck-terra-bucket" -backend-config="key=test.tfstate" -backend-config="region=ap-south-1"

      - name: Terraform Apply
        run: terraform apply --auto-approve


  Terraform_Destroy:
    name: "Terraform_Destroy"
    runs-on: ubuntu-latest
    needs: [Terraform_Apply]
    environment: Destroy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credetials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ap-south-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=ck-terra-bucket" -backend-config="key=test.tfstate" -backend-config="region=ap-south-1"

      - name: Terraform Destroy
        run: terraform apply -destroy --auto-approve
